# Generated by Django 4.2.9 on 2024-06-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='phone_no',
        ),
    ]
